replicaCount: 1
deploymentName: simpleservice
namespace: simpleservice
image:
  repository: wlanboy/simpleservice
  tag: latest
  pullPolicy: Always

hosts: 
  - simpleservice.tp.lan
  - simpleservice.gmk.lan

service:
  port: 4500

persistence:
  enabled: true
  size: 100Mi
  storageClass: local-path

istio:
  gateway: simpleservice-gateway
  gatewayNamespace: "istio-ingress"

certmanager:
  enabled: true
  issuer: local-ca-issuer
  kind: ClusterIssuer
  secretName: simpleservice-tls
